site_name: OMNI Help
site_url: https://help.omni.af.mil/ #Requires update
site_description: Support documentation for Operational Management Tools
site_author: ProjectBOCKSCAR 

#repo_url: http://help.bockscar.mil #Requires update
#edit_uri: ""

#dev_addr: help.omni.af.mil

theme:
    name: null
    custom_dir: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # mkdocs_theme.yml overrides
    language: en
    feature:
      tabs: true
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: bockscaricon.png
    logo: img/bockscar.png



nav:
    - Home: index.md
    - OMNI/PEX: 
        - 'user-guide/OMNI.md'
    - Mobile:  
        - Mobile Baseline : 'user-guide/MobileBaseline.md'
        - Updates : 'user-guide/Updates.md'
        - Sync GoodReader: user-guide/syncgoodreader.md
        - Troubleshooting : user-guide/troubleshooting.md
    - Contact Us: user-guide/Contacts.md
    - About: user-guide/About.md

#CSS overrides
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: 
#    - markdown.extensions.admonition
#    - markdown.extensions.def_list
    - admonition
    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

copyright: Copyright &copy; 2019 Project BOCKSCAR, Maintained by the Project BOCKSCAR Team.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
