site_name: OMNI Help
site_url: https://help.omni.af.mil/ 
site_description: Support documentation for Operational Management Tools
site_author: Project BOCKSCAR 

#repo_url: https://github.com/allebone/help.omni.af.mil
#edit_uri: ""

#dev_addr: help.omni.af.mil

theme:
    name: null
    custom_dir: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # mkdocs_theme.yml overrides
    language: en
    feature:
      tabs: true
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: 'bockscaricon.png'
    logo: 'img/omni.png'



nav:
    - OMNI: index.md
    - Status : Status.md
    - PEX: 
        - Pre Mission Processes : PEX/Premission.md
        - Post Mission Processes : PEX/Postmission.md
        - Formal Testing : PEX/Testing.md
#       - Current Status : PEX/CurrentStatus.md
    - Mobile:  
        - Mobile Baseline : Mobile/MobileBaseline.md
        - Doing Updates : Mobile/Updates.md
        - Syncing Pubs: Mobile/syncgoodreader.md
        - Troubleshooting : Mobile/troubleshooting.md
        - FAQ : Mobile/FAQ.md
    - Reports:  
        - Reports Description : Reports/Descriptions.md
        - Troubleshooting : Reports/troubleshooting.md    

#CSS overrides
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: true
#    - markdown.extensions.admonition
#    - markdown.extensions.def_list
    - admonition
    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

copyright: Copyright &copy; 2019, Maintained by the Project BOCKSCAR Team. (Version 1.0)

plugins:
    - search
    #- git-revision-date-localized


