site_name: OMNI Help
site_url: https://help.omni.af.mil/ 
site_description: Support documentation for Operational Management Tools
site_author: ProjectBOCKSCAR 

#repo_url: http://help.bockscar.mil #Requires update
#edit_uri: ""

#dev_addr: help.omni.af.mil

theme:
    name: null
    custom_dir: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # mkdocs_theme.yml overrides
    language: en
    feature:
      tabs: true
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: bockscaricon.png
    logo: img/bockscar.png



nav:
    - Home: index.md
    - PEX: 
        - Pre Mission Processes : 'user-guide/OMNI/Premission.md'
        - Post Mission Processes : 'user-guide/OMNI/Postmission.md'
        - Formal Testing : 'user-guide/OMNI/Testing.md'
        - Current Status : 'user-guide/OMNI/CurrentStatus.md'
    - Mobile:  
        - Doing Updates : 'user-guide/Mobile/Updates.md'
        - Syncing Pubs: user-guide/Mobile/syncgoodreader.md
        - Troubleshooting : user-guide/Mobile/troubleshooting.md
        - Mobile Baseline : 'user-guide/Mobile/MobileBaseline.md'
        - FAQ : 'user-guide/Mobile/FAQ.md'
    - Reports:  
        - Reports Description : 'user-guide/Reports/Descriptions.md'
        - Troubleshooting : user-guide/Reports/troubleshooting.md    

#CSS overrides
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: 
#    - markdown.extensions.admonition
#    - markdown.extensions.def_list
    - admonition
    - def_list
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs

copyright: Copyright &copy; 2019, Maintained by the Project BOCKSCAR Team. (Version 1.0)

plugins:
    - search
    #- git-revision-date-localized

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
