site_name: OMNI Help
site_url: https://help.omni.af.mil 
site_description: Support documentation for Operational Management Tools
site_author: Project BOCKSCAR 

#repo_url: https://github.com/allebone/help.omni.af.mil
#edit_uri: ""

#dev_addr: help.omni.af.mil
use_directory_urls: false
theme:
    name: null
    custom_dir: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # mkdocs_theme.yml overrides
    language: en
    feature:
      tabs: true
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: img/omni_contrail_icon_white_blue_background.png
    logo: img/omni_contrail_white_30x30.png

nav:
    - OMNI: 
        - About : index.md
        - Status : Status.md
    - PEX: 
        - Introduction : PEX/Introduction.md
        - Guides : PEX/Guides.md
        - Headquarters : PEX/Headquarters.md
        - Displays : PEX/Displays.md
        - Ops : PEX/Ops.md
        - Scheduling : PEX/Scheduling.md
        - Training : PEX/Training.md
        - Stan Eval : PEX/StanEval.md
        - Maintenance : PEX/Maintenance.md
        - Setup : PEX/Setup.md
        - Miscellaneous : PEX/Miscellaneous.md
    - Mobile:  
        - Introduction : Mobile/Introduction.md
        - Updates : Mobile/Updates.md
        - Syncing Pubs: Mobile/SyncingPubs.md
        - Email & Certs: Mobile/Email&Certs.md
        - Troubleshooting : Mobile/Troubleshooting.md
        - Outprocessing : Mobile/Outprocessing.md
        - FAQ : Mobile/FAQ.md
    - Reports:  
        - Introduction : Reports/Introduction.md
        - Reports Description : Reports/Descriptions.md
        - Troubleshooting : Reports/Troubleshooting.md
    - Support : 
            - Contact.md 

#CSS overrides
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: true
#    - markdown.extensions.def_list
    - admonition
    #- meta
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs
    #- attr_list
    #- pymdownx.smartsymbols
    #- pymdownx.inlinehilite
    #- pymdownx.details
    #- pymdownx.escapeall
    #- pymdownx.emoji
    #- pymdownx.extra
#   https://facelessuser.github.io/pymdown-extensions/extensions/extra/
#   pymdownx.exta includes (and conflics with) these extensions:
#   - pymdownx.betterem
#   - pymdownx.superfences
#   - footnotes
#   - attr_list
#   - def_list
#   - tables
#   - abbr
#   - pymdownx.extrarawhtml

copyright: Copyright &copy; 2020, Maintained by the Project BOCKSCAR Team. (Version 0.3)

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        time_zone: America/Chicago
        locale: en
        fallback_to_build_date: false
    - mermaid2

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js




