site_name: OMNI Help
site_url: https://help.omni.af.mil 
site_description: Support documentation for Operational Management Applications and Tools
site_author: Project BOCKSCAR 
repo_url: https://github.com/allebone/help.omni.af.mil
#edit_uri: ""

#dev_addr: help.omni.af.mil
use_directory_urls: false
theme:
    name: null
    custom_dir: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # mkdocs_theme.yml overrides
    language: en
    feature:
      tabs: true
    palette:
      primary: indigo
      accent: indigo
    font:
      text: Roboto
      code: Roboto Mono
    favicon: img/omni_contrail_icon_white_blue_background.png
    logo: img/omni_contrail_white_30x30.png

nav:
    - Home: 
        - About : index.md
    - PEX: 
        - Introduction : PEX/Introduction.md
        - Guides : PEX/Guides.md
        - Displays : PEX/Displays.md
        - OPS : PEX/OPS.md
        - Scheduling : PEX/Scheduling.md
        - Training : PEX/Training.md
        - Stan Eval : PEX/StanEval.md
        - Maintenance : PEX/Maintenance.md
        - Setup : PEX/Setup.md
        - Miscellaneous : PEX/Miscellaneous.md
    - Mobile:  
        - Introduction : Mobile/Introduction.md
        - Baseline (HW) : Mobile/HWBaseline.md
        - Baseline (SW) : Mobile/SWBaseline.md
        - Certs: Mobile/Certs.md
        - Email: Mobile/Email.md
        - FAQ : Mobile/FAQ.md
        - Outprocessing : Mobile/Outprocessing.md
        - Syncing Pubs: Mobile/SyncingPubs.md
        - Troubleshooting : Mobile/Troubleshooting.md
        - Updates : Mobile/Updates.md
    - Reports:  
        - Introduction : Reports/Introduction.md
        - Reports Description : Reports/Descriptions.md
        - Troubleshooting : Reports/Troubleshooting.md
    - Support : 
            - Contact.md
            - FAQ.md

#CSS overrides
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - footnotes
    - attr_list
    - pymdownx.superfences
    - markdown.extensions.footnotes
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.tables
    - markdown.extensions.abbr
    - markdown.extensions.md_in_html

copyright: Copyright &copy; 2020, Maintained by the Project BOCKSCAR Team. (Version 0.3)

plugins:
    - search
    - git-revision-date-localized:
        type: iso_datetime
        locale: en
    #- mermaid2

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js




